### ISSUE TITLE
Center "step 3" circle vertically in the view

### ISSUE THREAD

**Issue by DimaMukhin** [DimaMukhin/EmojiCutter#1]
![chrome_2018-09-28_21-49-58](https://user-images.githubusercontent.com/22819273/46241154-875f8780-c368-11e8-9400-1390bc62fa51.png)

Basically need to center the blue circle vertically

**Comment by Foberm** [comment]
I'd like to do this

**Comment by DimaMukhin** [comment]
Great! Go ahead. Let me know if have any questions or problems running the application. Have fun.

**Comment by nhulongctk35** [comment]
@DimaMukhin I fixed this issue in PR #6

**Comment by DimaMukhin** [comment]
re-opening, issue not fixed yet. feel free to change the structure of the view to implement this fix.
