### ISSUE TITLE
Change web app title

### ISSUE THREAD

**Issue by DimaMukhin** [DimaMukhin/EmojiCutter#2]
Change the web app title from "React App" to "Emoji Cutter"

![chrome_2018-10-01_18-38-10](https://user-images.githubusercontent.com/22819273/46324604-2d99d000-c5a9-11e8-91f2-1c625da582c5.png)

**Comment by mchlp** [comment]
Can I take this?

**Comment by DimaMukhin** [comment]
its all yours. good luck and thank you for helping
