### ISSUE TITLE
Implement auto scroll on "down arrow" click

### ISSUE THREAD

**Issue by DimaMukhin** [DimaMukhin/EmojiCutter#3]
Implement an automatic scroll down to the first stop of the application when the "down arrow" is clicked. See image below for more details.

![chrome_2018-10-01_18-41-28](https://user-images.githubusercontent.com/22819273/46324685-a00ab000-c5a9-11e8-88a5-0d2aa1f25fd9.png)

**Comment by dbrudner** [comment]
I'm checking it out!

**Comment by DimaMukhin** [comment]
awesome thank you!

**Comment by dbrudner** [comment]
https://github.com/DimaMukhin/EmojiCutter/pull/5
